version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    allow:
      - dependency-type: development
    directory: /
    groups:
      otel:
        patterns:
          - '@opentelemetry/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
    schedule:
      interval: weekly
    versioning-strategy: increase
