name: ci-cloudflare-access
on:
  push:
    branches: [main]
    paths:
      - 'packages/cloudflare-access/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/cloudflare-access/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cloudflare-access
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/cloudflare-access
      - run: yarn workspace @hono/cloudflare-access build
      - run: yarn test --project @hono/cloudflare-access
