name: ci-clerk-auth
on:
  push:
    branches: [main]
    paths:
      - 'packages/clerk-auth/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/clerk-auth/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/clerk-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn workspaces focus hono-middleware @hono/clerk-auth
      - run: yarn workspace @hono/clerk-auth build
      - run: yarn test --project @hono/clerk-auth
