name: ci-medley-router
on:
  push:
    branches: [main]
    paths:
      - 'packages/medley-router/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/medley-router/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/medley-router
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn workspaces focus hono-middleware @hono/medley-router
      - run: yarn workspace @hono/medley-router build
      - run: yarn test --project @hono/medley-router
