name: ci-oauth-providers
on:
  push:
    branches: [main]
    paths:
      - 'packages/oauth-providers/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/oauth-providers/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/oauth-providers
      - run: bun run --filter @hono/oauth-providers build
      - run: bun run --filter @hono/oauth-providers publint
      - run: bun eslint packages/oauth-providers
      - run: bun test --coverage --project @hono/oauth-providers
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: oauth-providers
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
