name: ci-otel
on:
  push:
    branches: [main]
    paths:
      - 'packages/otel/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/otel/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: bun run --filter @hono/otel build
      - run: bun run --filter @hono/otel publint
      - run: bun eslint packages/otel
      - run: bun run test --coverage --project @hono/otel
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: otel
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
