name: ci-otel
on:
  push:
    branches: [main]
    paths:
      - 'packages/otel/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/otel/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/otel
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/otel
      - run: yarn workspace @hono/otel build
      - run: yarn test --project @hono/otel
