name: 'good first issue'
on: [issues]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Hex/first-label-interaction@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-labels: '["good first issue"]'
