name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  what-changed:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    permissions:
      contents: "read"
      actions: "read"
      pull-requests: "read"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - run: bun install --filter ./ --filter ./scripts/what-changed
      - run: bun run what-changed
        id: set-packages

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - run: bun install
      - run: bun run publint
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run format

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version-file: .tool-versions
      - run: deno install --no-lock
      - run: deno publish --dry-run

  test:
    runs-on: ubuntu-latest
    needs: [what-changed]
    if: ${{ needs.what-changed.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.what-changed.outputs.packages) }}

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - run: bun install --filter ./ ${{ matrix.package.path }}
      - run: bun run build --filter ${{ matrix.package.path }}
      - run: bun run test --coverage --project ${{ matrix.package.name }}
        id: test
        if: ${{ matrix.package != 'eslint-config' && matrix.package != 'qwik-city' && matrix.package != 'react-compat' }}
      - uses: codecov/codecov-action@v5
        if: ${{ matrix.package != 'eslint-config' && matrix.package != 'qwik-city' && matrix.package != 'react-compat' }}
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: ${{ matrix.package.name }}
