name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Used by changests to create releases
      id-token: write # Used for authentication with both npm and jsr registries
      pull-requests: write # Used by changesets to create a pull request for the release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Build Cache
        uses: actions/cache@v5
        with:
          path: |
            .turbo
            packages/*/.cache
          key: ${{ runner.os }}-turbo-release-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-release-
            ${{ runner.os }}-turbo-

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version-file: .tool-versions
      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn turbo build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run publish
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
